name: LumiPay CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps


    - name: Build Next.js App
      run: npm run build
      env:
        # Provide env vars so the build doesn't fail during prerendering
        NEXT_PUBLIC_GOLDSKY_URL: "https://dummy-url"
        GEMINI_API_KEY: "dummy-key"
        NEXT_PUBLIC_PRIVY_APP_ID: "cmps8wpr000iy0dl169ookgrn"
        PRIVY_APP_SECRET: "dummy-privy-secret"
        RESEND_API_KEY: "dummy-resend-key"
        CRON_SECRET: "dummy-cron-secret"
        PRIVATE_KEY: "0x0000000000000000000000000000000000000000000000000000000000000001"
